id: P2C428489
initial_creation_type: ocr
source_metadata:
  volumes:
    7293ac69a72846fc8cddd5fce873cd04:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རལ་པ་གཅིག་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
